### ISSUE TITLE
Ability to drag selected component around in the overlay

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#1]
Requires implementing `wasMoved` in the `componentMovedOrResized` callback.

The hard part will be making sure this doesn't screw up any UX "feel".

**Comment by dikadk** [comment]
I've added dragging of selected component within TopLevelComponent Bounds().

I had to move component selection from mouseDown() to mouseUp(). I don't think this makes UX any worse, but makes dragging logic simpler. Let me know your thoughts on this

https://user-images.githubusercontent.com/15266737/204887037-be02ebdc-b64e-4cfe-9a39-650242b32a6b.mp4

**Comment by sudara** [comment]
Super pumped about this, thank you!
