### ISSUE TITLE
Holding alt when component is selected shows distance to parent or hovered element

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#10]
This is a direct copy of behavior in Figma. Happy to provide an example file for exploring and matching behavior.

Basically, this changes the behavior of the overlay *when alt is held*

## Spacing to parent

When 

1. a component is selected
2. hovering over self or parent

then show spacing to parent.

* Additional red outline around selected component
* A red line connects the midpoint of each components side to the parent (so, in all 4 directions)
* Red backgrounded labels midway on each line displaying distance in logical pixels

![Screenshot 2021-04-20 Pluginz - Figma](https://user-images.githubusercontent.com/472/115388937-c9799e80-a1dc-11eb-936b-99f1a9b489fd.jpg)

## Spacing to hovered element

When 

1. a component is selected
2. hovering over *another component*

Show spacing to hovered element.

This requires:

* Red bounding boxes on selected AND hovered component
* Determining if vertical or horizontal line is best
* Line from middle of source element edge (as usual)

![Screenshot 2021-04-20 Pluginz - Figma](https://user-images.githubusercontent.com/472/115388814-99ca9680-a1dc-11eb-95e6-a4f1fdb3b805.jpg)

* In the case that the elements only connect diagonally, draw dotted line at right angle to target  
* 
![Figma - 2022-11-24 17@2x](https://user-images.githubusercontent.com/472/203840841-fb551802-fa95-4363-b288-6ea6eaffb550.jpg)

**Comment by dikadk** [comment]
I've been making some progress on this one. WIP demo 


https://user-images.githubusercontent.com/15266737/207496398-5981dc7c-9d8c-4472-86f3-d2e0ceddddc6.mov

**Comment by sudara** [comment]
This is such an awesome feature
