### ISSUE TITLE
The inspector's tree view is selectable as an inspectable component

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#107]
This shouldn't be possible and seems to be consistently reproducible when clicking back to the tree from the UI. 

Probably related to recent accessibility changes

![Sine Machine v14 - 2024-03-30 51@2x](https://github.com/sudara/melatonin_inspector/assets/472/df3253bf-3110-4bc1-83b4-11ccdcfdba72)

**Comment by baconpaul** [comment]
This is in mouse mode not focus mode?

**Comment by sudara** [comment]
Yes. Haven’t looked into it at all, was deep in UI land…

**Comment by sudara** [comment]
I'm dumb, this was on the `keyboard_toggle` branch (#103) that I thought was merged but was not yet...
