### ISSUE TITLE
Clicking a component in the overlay should always highlight and vertically center in the tree view

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#17]
Some sort of bug with this
![AudioPluginHost - 2022-11-24 11](https://user-images.githubusercontent.com/472/203838670-cb61109a-63a4-4b8e-985b-7159367ac15a.gif)

**Comment by dikadk** [comment]
Fixed in _develop_. 

Ignore flicker, I have gap between yellow components, so selection jumps to MultiPanelComponent.

https://user-images.githubusercontent.com/15266737/204687644-f2a90abf-a80e-4879-a5c5-60573f5feaf7.mp4
