### ISSUE TITLE
Setup a "property editor" box

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#20]
To start, this could show:

* *editable* x/y
* editable width/height
* is opaque?
* has a cached image?
* alpha
* focus state

Probably we want to put the tree view in its own column and put properties under the box model? Could play with it, maybe properties in their own col also ok.

I want to "collapse" (aka remove the extra column) when "enabled" is unchecked.

![Image](https://user-images.githubusercontent.com/472/203847814-b613c55f-b754-4608-a349-d23558bb1f20.jpg)

Look at chrome "inspector" for initial guidance on the properties view (no "filter" or disclosure triangle needed, can just theme the JUCE property editor)
![Google Chrome - 2022-11-24 11@2x](https://user-images.githubusercontent.com/472/203845559-15b7cce5-aeb0-492e-a51f-80bf17e6ab10.jpg)

**Comment by dikadk** [comment]
That was a great idea to use juce::PropertiesPanel, it simplified adding new properties a lot 👍 

Available on _**develop**_. I don't have any visual way to separate editable vs non-editable properties in the menu. Maybe we can come up with something to make it more obvious.

https://user-images.githubusercontent.com/15266737/205415124-c0dd1824-e2b1-4cb9-82ed-4fdab389e76f.mp4
