### ISSUE TITLE
Search Field "filter" for Component names

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#21]
I'd like a search box above the tree view which:

* has placeholder "search" text
* when text is typed, an underlined link appears to the right of the box "_clear_"
* pressing enter is not required, typing text should live filter the component names
* if a "leaf node" matches the search query, the entire parent hierarchy is kept
* Otherwise the node is removed from the tree
* The first result is highlighted (also selected in the overlay)
* If there's no match, "No component found" text appears vertically and horizontally centered 

![Image](https://user-images.githubusercontent.com/472/203846653-48e22011-e664-450e-8173-cde53ec8e10d.jpg)

**Comment by dikadk** [comment]
Added "search" functionality and it's available on _**develop**_ 

https://user-images.githubusercontent.com/15266737/205470019-8c86e9b2-b864-4571-87dd-6572445fd1b1.mp4

**Comment by sudara** [comment]
Amazebar!
