### ISSUE TITLE
Color inspector should display RGBA values

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#26]
I use uint8 RGBA most often inside projects, ala `Colour::fromRGBA (255,255,255,255)`

Right now there's a text editor there — is that doing anything at the moment?

**Comment by dikadk** [comment]
This was updated and available on develop

https://user-images.githubusercontent.com/15266737/207150543-0a876938-ff3f-4b2b-94d2-98435e10ac1c.mov
