### ISSUE TITLE
Deselecting an element should select root (vs. hide tree). Blank slate moves to properties

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#27]
I think this is a regression on develop right now, the tree view should ideally never be blank, as I might want to select or search the tree for the element (vs. select in the UI)

![Image](https://user-images.githubusercontent.com/472/205655015-624aecc2-1a56-4560-bfe4-66580023276f.png)

I do like the blank slate for the selection though — ideally that that blank slate belongs in the properties tab.

**Comment by dikadk** [comment]
I pushed quick fix to **_develop_**. It should unblock using develop.
