### ISSUE TITLE
Trouble with CMake configuration on MSVC

### ISSUE THREAD

**Issue by jatinchowdhury18** [sudara/melatonin_inspector#38]
First off thanks for creating this tool! It's been quite useful for me so far, and I feel like I'm just scratching the surface.

I've had a slight issue with CMake configuration when building with MSVC. I was adding the JUCE module from CMake using `add_subdirectory(melatonin_inspector)`, which causes the CMake configure command to fail when generating a Visual Studio project, with the following error:
```
CMake Error: Cannot open file for write: D:/a/ChowMultiTool/ChowMultiTool/build/modules/melatonin_inspector/Melatonin::Inspector.sln.tmp480a3
CMake Error: : System Error: Invalid argument
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

The issue is that the CMake proejct name is `Melatonin::Inspector`, which I guess is an illegal file name for a MSVC .sln (likely because of the double colon).

Anyway, I can get around it pretty easily by doing a `juce_add_module` instead, but I figured I'd mention it just in case you hadn't seen this issue yet.

**Comment by sudara** [comment]
Hey Jatin!

Thanks for the report! I've actually seen this msvc sln issue but it's been intermittent when I've cleared caches!

Thanks for catching this, it was my intention to make the project name with colons, that was just supposed to be the added alias!

Hope the inspector is helpful and just shout if you run into other issues or ideas.
