### ISSUE TITLE
Add toggle for dragging and resizing components

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#49]
Figure out a way to disambiguate (defer dragging to the app by default?)

**Comment by reFX-Mike** [comment]
Since it also resets the transforms, I would prefer if the whole dragging/resizing feature could be toggled on off.

**Comment by sudara** [comment]
Yeah agreed. Moving and resizing might be better as explicitly enabled. Between this and wanting to disable the overlay entirely, I’m starting to feel toolbar vibes…
 
just keep thinking (along with #50) that there might be a better mental model of what “inspector is enabled” means…

**Comment by reFX-Mike** [comment]
I would steal as much behavior/decisions as possible from established tools, like the chrome inspector. The closer we can get to that, the better. Is familiar and there are often good reasons why things are the way they are.

Maybe even add a “console” for debugging messages (we can add our own log macro).

**Comment by sudara** [comment]
> Is familiar and there are often good reasons why things are the way they are.

Yes, the tool is modeled on figma and safari/chrome web inspector, so 100% with you on that! Devil is in the details though, in particular because the tool started from 0 (for example moving components didn't exist) and is evolving incrementally.

> Maybe even add a “console” for debugging messages

Tell me more! What benefits does this bring on top of IDE logging with `DBG`? Timestamps? Retention across sessions?

**Comment by reFX-Mike** [comment]
Retention in general, and we use multiple different macros Z_LOG for pure debugging, does nothing in release builds, but Z_WARN and Z_ERROR are always logged and visible to customers.

we can then collate that last 3-4 sessions into one text file and save it. That way customers can provide these to aid in trouble shooting.

**Comment by sudara** [comment]
Icons are already in place for this in the BinaryData

![Figma - 2023-09-06 51@2x](https://github.com/sudara/melatonin_inspector/assets/472/16039f0d-7513-4d26-8a2b-adbd42055be4)
