### ISSUE TITLE
Show font size and colors when possible

### ISSUE THREAD

**Issue by sudara** [sudara/melatonin_inspector#9]
This will only apply to some default juce stuff?

**Comment by sudara** [comment]
Don't bend over backwards (yet) to make this editable — mainly want to show what's in use. 

Ideally colors are displayed in RGBA values by default?

**Comment by dikadk** [comment]
I've added Color inspector and small widget for showing component image snapshot. I'm not super happy about it's position though. Where do you think it should be? Above or under properties? Also let me know if you have completely different vision for this "widget"?

Available on _**develop**_

![Image](https://user-images.githubusercontent.com/15266737/205418851-9e10215b-cf39-402a-b0bc-372252a45eee.png)
