### ISSUE TITLE
Selection lock

### ISSUE THREAD

**Issue by FigBug** [sudara/melatonin_inspector#90]
I need to be able to click around in my UI without losing the component I'm currently looking at. A switch to disable the overlay while keeping the inspector active?

**Comment by sudara** [comment]
I like the concept of a lock. Maybe as an icon available on hover in the tree view? Is it good enough if “click to select” behavior is disabled and overlay remains? (selected component border could turn red to help indicate)

Intersects a bit with #74 and #49

**Comment by sudara** [comment]
#103 contains a basic implementation for this. It disables selection and hover outline.

An followup improvement could be "if nothing was selected, the next selected item gets locked".
